### ISSUE TITLE
template_rpc requires bib files to be in alternative location

### ISSUE THREAD

**Issue by tymorrow** [kohoman/mstTheses#2]
Would it be better if we could just pull the repository and immediately build without needing to put the bib files in `$(HOME)/texmf/bibtex/bib`?

I know, at least for me, I tend to have my bib files in the same directory so they remain under version control.

**Comment by kohoman** [comment]
Yes, that would be fine.  I have now added the mstogs.bst files in both the rpc template directory and the pto template directory.

Kelly Homan

**Comment by kohoman** [comment]
Addressed as of today's update.
